FUNCTION z_fb_1340.
*"----------------------------------------------------------------------
*"*"Lokale Schnittstelle:
*"  IMPORTING
*"     VALUE(I_KNA1) LIKE  KNA1 STRUCTURE  KNA1
*"     VALUE(I_KNB1) LIKE  KNB1 STRUCTURE  KNB1
*"     VALUE(I_KNA1_OLD) LIKE  KNA1 STRUCTURE  KNA1
*"     VALUE(I_KNB1_OLD) LIKE  KNB1 STRUCTURE  KNB1
*"     VALUE(I_KNVV) LIKE  KNVV STRUCTURE  KNVV
*"  TABLES
*"      T_XKNBK STRUCTURE  FKNBK
*"      T_XKNB5 STRUCTURE  FKNB5
*"      T_YKNBK STRUCTURE  FKNBK
*"      T_YKNB5 STRUCTURE  FKNB5
*"      T_XKNZA STRUCTURE  FKNZA
*"      T_YKNZA STRUCTURE  FKNZA
*"      T_XKNAS STRUCTURE  FKNAS OPTIONAL
*"      T_YKNAS STRUCTURE  FKNAS OPTIONAL
*"      T_XKNEX STRUCTURE  FKNEX OPTIONAL
*"      T_YKNEX STRUCTURE  FKNEX OPTIONAL
*"      T_XKNVA STRUCTURE  FKNVA OPTIONAL
*"      T_YKNVA STRUCTURE  FKNVA OPTIONAL
*"      T_XKNVD STRUCTURE  FKNVD OPTIONAL
*"      T_YKNVD STRUCTURE  FKNVD OPTIONAL
*"      T_XKNVI STRUCTURE  FKNVI OPTIONAL
*"      T_YKNVI STRUCTURE  FKNVI OPTIONAL
*"      T_XKNVK STRUCTURE  FKNVK OPTIONAL
*"      T_YKNVK STRUCTURE  FKNVK OPTIONAL
*"      T_XKNVL STRUCTURE  FKNVL OPTIONAL
*"      T_YKNVL STRUCTURE  FKNVL OPTIONAL
*"      T_XKNVP STRUCTURE  FKNVP OPTIONAL
*"      T_YKNVP STRUCTURE  FKNVP OPTIONAL
*"      T_XKNAT STRUCTURE  FKNAT OPTIONAL
*"      T_XKNBW STRUCTURE  FKNBW OPTIONAL
*"      T_YKNAT STRUCTURE  FKNAT OPTIONAL
*"      T_YKNBW STRUCTURE  FKNBW OPTIONAL
*"----------------------------------------------------------------------

  IF i_kna1-name1 = 'Mustermann'.
    MESSAGE 'Treffer bei Mustermann' TYPE 'I'.
  ENDIF.
ENDFUNCTION.
